### ISSUE TITLE
Japanese Holidays in English from 2019

### ISSUE THREAD

**Issue by moon73** [microsoft/AddOutlookJapanHoliday#1]
Hello,

Wonder if there is a script in English. Where I work, we've been using Outlook with English version. This script can't be run due to language... 

Appreciate your help if possible and thank you for sharing this.

![image](https://user-images.githubusercontent.com/51103315/58445737-b963fc00-8138-11e9-8804-19d73e462620.png)

**Comment by rykoma** [comment]
Hi @moon73 ,

Thank you for your feedback.
It seems that we need to add English environment support. I'll work on this and update the script in the near future.

**Comment by rykoma** [comment]
Hi @moon73 ,

I added an English version script. You can download the file from here.
https://github.com/microsoft/AddOutlookJapanHoliday/releases/download/PreRelease/AddHolidays_en.zip

I hope this script works for you. Let me know if you have any problems on this script.
Especially, let me know if you are using Outlook in English and the names of holidays are Japanese. This script expects the environment that Outlook in English and the names of holidays are also English.

**Comment by moon73** [comment]
Hi @rykoma,

This worked perfect! Much appreciated. You saved me! :)

The script successfully run in the following environment, Outlook in Eng + Holidays in Eng + Windows in Eng. This is what I expected exactly. Can't thank you enough. I will distribute this to end users. Again, thanks a lot for your quick help.

![image](https://user-images.githubusercontent.com/51103315/58542269-3a55ed00-8238-11e9-8b63-b1471759d5e8.png)

**Comment by moon73** [comment]
Closing...

**Comment by rykoma** [comment]
I'm glad to hear that!
I added the English script to the latest release.
https://github.com/microsoft/AddOutlookJapanHoliday/releases/download/v1.1/AddHolidays_en.zip

Thank you again for your feedback.
