### ISSUE TITLE
"大みそか" is not Japanese national holiday

### ISSUE THREAD

**Issue by elfham** [microsoft/AddOutlookJapanHoliday#5]
According to [Japanese law](https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html), "大みそか" is not Japanese national holiday.

https://github.com/microsoft/AddOutlookJapanHoliday/blob/50d3822565ec6b4b28bd627b1a9bf56a9f256211/OUTLOOK.HOL#L7418-L7430

**Comment by rykoma** [comment]
@elfham , thank you for your comment.

In general the current Outlook holiday data contains a mix of non-holiday type events as well as official public holidays to provide a richer experience for customers. "大みそか" falls into the non-holiday category and is present in the events data for many of the regions, including Japan, although it's not a formal holiday.
